language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8 # stable
  - 6 # LTS
  - 4 # maintainance
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
